### ISSUE TITLE
3D Secure Payment - Stripe

### ISSUE THREAD

**Issue by gfyre** [Viveckh/Veniqa#115]
How come a " 3D Secure" Stripe Test card does not work? It shows the following in console:

`POST https://veniqa-client-server-prod.azurewebsites.net/orders/completeCheckoutUsingCard 400 (Bad Request)`

Try using card number "4000 0000 0000 3220"

When checking out, the only thing that is asked is the card number, expiry date and CVV. Why isn't the Name of the CardHolder or any of those details asked?

**Comment by gfyre** [comment]
@Viveckh @smaharj1 Please help me out here. Thanks.

**Comment by Viveckh** [comment]
Hey @gfyre,
Are you trying this on the demo site or your own local instance of the app? I'm going to assume it's the demo site since the requests are being redirected to our demo server.

And are you using test Stripe API keys or production ones? The payment is handled through Stripe, so if other cards are passing payments but this particular one is failing, then we probably won't be of any help here.

The reason we didn't ask for the Card Holder Info was that it wasn't a required input for stripe payments to work. In hindsight, probably should have, even if just for the verification.

**Comment by Viveckh** [comment]
Also some additional insights [here](https://github.com/Viveckh/Veniqa/issues/116#issuecomment-629814482), which might be helpful.

**Comment by gfyre** [comment]
Hey @Viveckh, the card that I mentioned was a test card I found over on Stripe's website. It requires authentication for a payment to go through 

I tried running Veniqa on a local instance with my Stripe Test keys and the issue is the same. 

The cards which do not require 2 step authentication go through just fine however its the cards that require 2 step Auth that are causing a problem (countries in Europe apparently require 2 step Auth)

**Comment by Viveckh** [comment]
Yes, so Multi-Step Auth for payments isn't something supported on the platform currently, so you'd have to implement that by updating the payment flow on the `shopping-webclient` to account for that, as I outlined in the link above.

**Comment by gfyre** [comment]
@Viveckh could you help me out by directing me to the files where I'd implement it. That would save me some time. 

Thanks.

**Comment by Viveckh** [comment]
@smaharj1 would be the best person to answer this, since it's on the webclient.

**Comment by gfyre** [comment]
@smaharj1 Could you please advice where to insert the code for Stripe MFA (PaymentsIntent)?

Thanks.

**Comment by smaharj1** [comment]
@gfyre please follow the trails of `PaymentDetail.vue`

**Comment by AmandaDLyon** [comment]
@gfyre refer to this #116
