### ISSUE TITLE
New order does not show in admin dashboard

### ISSUE THREAD

**Issue by AmandaDLyon** [Viveckh/Veniqa#117]
**Describe the bug**

When a new order is placed, it does not show up in the Admin dashboard. 

**To Reproduce**
1. Place a new order
2. Sign into dashboard
3. The new order does not show

**Expected behavior**

The order must show on the dashboard and I should be able to filter between the condition of the order. As in, completed orders should be separated from pending orders.

**Additional context**

I logged in with veniqademo@gmail.com and password was pass$12 on my local system. I accidentally deleted the super admin accounts (oops!)

However, I am able to make changes to the featured section of the homepage through the aforementioned credentials.

**Comment by smaharj1** [comment]
I believe this is because of the pagination feature on the Orders page. There are probably more than 10 orders already made. This feature is yet to be developed from web application side. 

About deleting your super admin account in **local**, you can make changes in Featured section of the admin dashboard, but you can't save it. We decided to enable this to showcase the application's dashboard side features. If this is not what you were talking about, when you use Docker, we are restoring the "original" data every time you do a fresh start of docker. You can change the setting any way you want from the mongo dockerfile.

**Comment by AmandaDLyon** [comment]
@smaharj1 so what would be the work-around to the pagination issue? Is it possible for me to simply lift how many orders can be seen on one page?

And once an order is marked as completed/fulfilled, where does it go? What happens to it?

**Comment by smaharj1** [comment]
@AmandaDLyon the api capability is there. Only the UI doesn't have 'next page'/'previous page' functionality. You can simply accomplish this by adding pagination and when you make api calls to get orders, give paging info.
