### ISSUE TITLE
BUG: Issue with Safari not passing cookie/session info

### ISSUE THREAD

**Issue by gfyre** [Viveckh/Veniqa#124]
**Describe the bug**
Platform sort of crashes when using on iOS web browsers. Checked on Safari, Chrome, Google App, Cake and Opera Touch

**To Reproduce**
1. Go to shop.veniqa.com
2. Login or Sign Up
3. Try adding a product to cart (at this point, nothing will happen)
4. Refresh the page (at this point, you will be logged out)

**Expected behavior**
It should work normally how it does on the desktop version. 

**Smartphone (please complete the following information):**
 - Device:  iPhone X
 - OS: iOS 13.2
 - Browser Safari, Chrome, Cake, Opera Touch
 - Version Latest Stable

**Comment by AmandaDLyon** [comment]
@Viveckh @smaharj1 Hey guys, I see that you have fixed the pagination issue on the management platform. Thanks for that. 

I checked for the issue that @gfyre has mentioned and it turns out that I am facing it as well.

**Comment by smaharj1** [comment]
The issue seems to be causing due to local storage. Opening up this bug ticket for anyone to grab it.

**Comment by gfyre** [comment]
This might not be a local storage issue. It seems that the request is unauthorised (Code 401). Refer to the screenshot. Might help with fixing the bug. This is the JS Console in Safari running on MacOS.

<img width="1277" alt="Screenshot 2020-06-20 at 10 29 20 PM" src="https://user-images.githubusercontent.com/23535062/85207323-9c065f00-b345-11ea-976a-dffbaab9cd45.png">

**Comment by smaharj1** [comment]
@gfyre thanks. Yes. It is because for some reason Safari doesn't pass session info through every request.

**Comment by gfyre** [comment]
@smaharj1 so what can be done here? how would you fix this?

**Comment by AmandaDLyon** [comment]
@smaharj1 is there a fix for this issue?

**Comment by AmandaDLyon** [comment]
https://stackoverflow.com/questions/60020416/axios-requests-using-authentication-token-sometimes-fail-in-safari 

This might help

**Comment by smaharj1** [comment]
@AmandaDLyon I'll have to look into this.

**Comment by Viveckh** [comment]
We've noticed this previously and there is a pending issue for it #10 

It seems to happen because of iOS blocking cross-domain requests when the API endpoints and the frontend belong to two different domains. For our demo sites, the frontend domains are in the form *.veniqa.com whereas the API endpoints are in the form *.azurewebsites.net. And by default, iOS seems to block session info from being passed to endpoints outside the site domain.

We didn't find any workarounds to this since it seems to be from the iOS level, but the solution is to have your API endpoints and website in the same domain and preventing cross-domain requests.

I'll try and set up custom *.veniqa.com subdomains for our demo API endpoints to prevent this from happening.

**Comment by gfyre** [comment]
@Viveckh I setup everything on a local environment and tested an entire cycle that a customer would follow in order to make a purchase on Safari.

I can confirm that running the front-end and the server side API on the same domain does indeed fix this issue. 

Thanks for making us aware about this solution. 

If you'd like, you can close this issue or leave it pinned for any other user to refer to. Please make a call here.

**Comment by Viveckh** [comment]
UPDATE: The Veniqa demo servers are now hosted on the same domain as the frontend. With that, the issue of session cookies not being passed is resolved. Since chrome seems to have introduced a similar breaking change of disallowing cross-domain cookies, it is highly recommended for any developers adopting Veniqa to host all the components in the same domain moving forward.
