### ISSUE TITLE
Admin Login Credentials 

### ISSUE THREAD

**Issue by sai-koumudi** [Viveckh/Veniqa#147]
![Screenshot (846)](https://user-images.githubusercontent.com/72659783/100477390-31d0c200-310e-11eb-817f-58772c96d3e0.png)
I've gone through the document and added the necessary keys in the .env.format file. I was somehow unable to login with the demo admin credentials provided in the document. (Email: veniqademo@gmail.com, Password: pass$12)

Also, the deployed one has the same issue (https://admin.veniqa.com/#/login)
Are there any other credentials or ways to register as admin? 

Thanks in advance!!

**Comment by vipuluthaiah** [comment]
i am too facing same
issue

**Comment by Viveckh** [comment]
Hey guys, there were some issues in the live demo site due to our SSL certificates expiring.
It is addressed now, so you should be able to use the demo site.

I am working on a db migration to Mongo Atlas due to the closure of Mlab.com, so you might experience a little downtime for a day or two on the live demo.

P.S. The credentials you have included up there is only applicable for the live demo - it is of a view-only user. For your local setup, a super-admin user is available by default if you started with the mongo dump we provide. The credentials for this user can be found in [this link](https://documentation.veniqa.com/dockersetup/dockersetup.html#default-logins) 

If this addresses your concern, please do close the issue.
