### ISSUE TITLE
how to setup admin accounts

### ISSUE THREAD

**Issue by myminseok** [Viveckh/Veniqa#87]
Hi, this artifact is pretty nice work!. I tried to run this, but wonders how to set up admin accounts?
I tracked the source code and it might be around on mongodb collections. but not sure how what exact schema is.
 Please give some hints on documentations

**Comment by xtermsoft** [comment]
How do I create new admins for the management dashboard? I have the platform up and running however I am unsure as to how to create these new users.

**Comment by Viveckh** [comment]
If you navigate to the `Users Setting` section of the admin dashboard, you should see a `+ADMINS` button at the top right section of the page. You can use the form to create new admins and assign them granular permissions.  [](url)
![Screen Shot 2020-04-18 at 5 58 36 PM](https://user-images.githubusercontent.com/9113166/79672258-4d4e1480-819e-11ea-9007-29859967e7e7.png)

**Comment by xtermsoft** [comment]
I am not able to log into the admin panel itself. I am running the whole stack locally. In the browser dev console, it says error connecting with localhost:4202.I have attached the screenshot of the same.
<img width="766" alt="Screenshot 2020-04-19 at 12 46 16 PM" src="https://user-images.githubusercontent.com/23535062/79681916-db2c0d00-823b-11ea-9b33-eacb81c08728.png">

What is running on port 4202? And how do I add new users to the admin dashboard? 

What is being hosted on "https://veniqa-client-server-prod.azurewebsites.net" and "https://s3.amazonaws.com/veniqa-catalog-images/permanent-thumbnails" ]

Thanks a lot for your help.

And when I add the products through the admin panel, they would show up on the customer web-client right?

**Comment by xtermsoft** [comment]
That along with a but load of Express + DB errors
<img width="611" alt="Screenshot 2020-04-19 at 2 59 35 PM" src="https://user-images.githubusercontent.com/23535062/79684379-6ca47a80-824e-11ea-8a19-2e7ed4df6e68.png">

Please guide me as I am really new to this framework. Thanks.

**Comment by smaharj1** [comment]
> https://veniqa-client-server-prod.azurewebsites.net

Please look into creating [environment files section](https://documentation.veniqa.com/servers/environment-file-format.html) in the documentation to create the `.env.development` file in the root of both of the server directories i.e. `/management-server` and `/shopping-server`. In the folders, you should already see a `.env.format` file that holds the format of the environment file. 

The server isn't running likely because of that file. The minimum keys you need to locally run the servers are `VENIQA_CRYPTO_SECRET_KEY` and `VENIQA_SESSION_SECRET_KEY`. After that you should be able to run the server and you won't see that error anymore. 

---

> What is being hosted on "https://veniqa-client-server-prod.azurewebsites.net" and "https://s3.amazonaws.com/veniqa-catalog-images/permanent-thumbnails" ]

These are the environment variables in `.env.production` in the frontend folders. they are basically saying that the `BASE_URL` for API is https://veniqa-client-server-prod.azurewebsites.net and for Veniqa, we are saving the images in S3 buckets. So, the s3.amazonaws.com link you see is pointing to the base URL of where to fetch the images from.

---

Coming in next release:
- Removing `.env` files from local development so that docker handles all of that.

**Comment by smaharj1** [comment]
> That along with a but load of Express + DB errors
> <img alt="Screenshot 2020-04-19 at 2 59 35 PM" width="611" src="https://user-images.githubusercontent.com/23535062/79684379-6ca47a80-824e-11ea-8a19-2e7ed4df6e68.png">
> 
> Please guide me as I am really new to this framework. Thanks.

I have created an issue for this. This is an issue of hot-reloading the servers in docker. We are looking into this issue. However, this should not stop your server. Master worker will still work and the request to your request (localhost:4202) will still be fetched. 

Workaround: 
```
docker restart <container>
```

**Comment by smaharj1** [comment]
Closing this since the issues were resolved.

**Comment by Viveckh** [comment]
We just pushed some updates related to the docker setup. If you refer to the [Docker Setup Guide](https://documentation.veniqa.com/dockersetup/dockersetup.html), it should answer your question in regards to the default admin user.
