### ISSUE TITLE
CORS + Sockets for Authentication

### ISSUE THREAD

**Issue by xtermsoft** [Viveckh/Veniqa#98]
**Describe the bug**
While running the entire stack, post filling up the values in`.evn.development` file, the whole stack loaded up, however, when an attempt is made to log into the admin dashboard, there is a CORS restriction. Please refer to the screenshot below.

**To Reproduce**
1. `docker-compose up`
2. Navigate to  http://localhost:5202/
3. login with any credentials
4. take a look at the console logs

**Expected behavior**
No POST errors

**Screenshots**
<img width="1060" alt="Screenshot 2020-04-20 at 6 37 51 PM" src="https://user-images.githubusercontent.com/23535062/79756842-e1ec7a00-8338-11ea-9c3f-85429f07ce3a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Google Chrome
 - Version: Latest

**Additional context**
What are the default admin credentials and how do you set new ones? I went into mongodb and created a new document following the schema from https://github.com/Viveckh/Veniqa/blob/develop/management-server/database/models/user.js#L6 here. 

Please assist. Thanks.

**Comment by smaharj1** [comment]
The CORS error is happening because your admin dashboard (localhost:5202) is trying to send a login request to shopping-server (localhost:4201). In your `/management-webclient`, it seems like you changed the base URL in `.env` files. Please put the base URL to be 

`VUE_APP_API_BASE_URL=http://localhost:4202/`

@Viveckh can you give more info on creds.

**Comment by smaharj1** [comment]
Closing this issue @xtermsoft since the new changes should resolve your problems.

**Comment by xtermsoft** [comment]
@smaharj1 @Viveckh I am reopening this issue since the following credentials seems to be incorrect:

Username: demo@veniqa.com
Password: pass$12

Please refer to the screenshot attached. Also, what's up with the socket connections being refused? I made the change to `/management-webclient` and `/management-server`as mentioned in @smaharj1 's comment above. Thanks for all your help.

<img width="1068" alt="Screenshot 2020-05-01 at 12 09 58 PM" src="https://user-images.githubusercontent.com/23535062/80787760-09e3a500-8ba5-11ea-972a-72e7f2074949.png">

**Comment by smaharj1** [comment]
> @smaharj1 @Viveckh I am reopening this issue since the following credentials seems to be incorrect:
> 
> 
> 
> Username: demo@veniqa.com
> 
> Password: pass$12
> 
> 
> 
> Please refer to the screenshot attached. Also, what's up with the socket connections being refused? I made the change to `/management-webclient` and `/management-server`as mentioned in @smaharj1 's comment above. Thanks for all your help.
> 
> 
> 
> <img width="1068" alt="Screenshot 2020-05-01 at 12 09 58 PM" src="https://user-images.githubusercontent.com/23535062/80787760-09e3a500-8ba5-11ea-972a-72e7f2074949.png">
> 
> 

Have you tried deleting the mongo docket images and containers? And did you pull the latest? 

I’ll look into socket error in a bit

**Comment by gfyre** [comment]
Alright, so I deleted all all the old containers and installed the latest version. Now I am able to log in, however there are a few issues: 

1. I keep on getting logged out of the dashboard. After some time, it just doesn't allow me to do anything and refreshing the page logs me out. 

2. When adding arrays to the product page, the array window is not readable (please refer to the screenshot) 

3. I am not able to make changes to the existing product or add a new product but I am assuming that it is because I dont have write access to your S3 database (the console log shows CORS errors for AWS S3. Refer to the screenshot)

4. When a new admin is added, what password would they use to log in, as I am not asked to enter a new password


<img width="1277" alt="Screenshot 2020-05-02 at 2 50 13 PM" src="https://user-images.githubusercontent.com/23535062/80860410-1f300080-8c85-11ea-8c41-4633e0b31804.png">
<img width="1266" alt="Screenshot 2020-05-02 at 2 50 37 PM" src="https://user-images.githubusercontent.com/23535062/80860414-21925a80-8c85-11ea-8bd9-6f2e808a845a.png">
<img width="665" alt="Screenshot 2020-05-02 at 2 54 25 PM" src="https://user-images.githubusercontent.com/23535062/80860417-222af100-8c85-11ea-89ef-b8a29bcec25e.png">
<img width="1280" alt="Screenshot 2020-05-02 at 2 56 19 PM" src="https://user-images.githubusercontent.com/23535062/80860418-235c1e00-8c85-11ea-8523-b3276e97d1cc.png">


Thanks alot for your help buddy! Really really appreciate it!

**Comment by smaharj1** [comment]
@xtermsoft 

1. You get logged out after some inactive time. It is intended. 

2. The fix is out there. #107 Thank you for bringing that up. 

3. For S3, you will have to point it to your own S3 buckets. We can't give the bucket access for local development. You need to create your buckets and update the info in `management-server/config.json`. Then, you'd need to update the URL in `.env` file in `management-webclient` too to point to your S3 bucket.

4. Please be patient with this one. We don't have a quick fix. Currently, the new account only works with proper nodemailer and sendgrid setup. If you have already configured those, then you should navigate to `management-server/.env.development` and add these keys:
<img width="425" alt="Screen Shot 2020-05-03 at 2 07 13 AM" src="https://user-images.githubusercontent.com/8810802/80907212-ff2f2a00-8ce2-11ea-95b1-ac3c6fdb5af2.png">

You can also add these keys in your `docker-compose.yml` file under management-server environment variable

**_Note: Please open a new issue for separate issues. It is hard to track multiple issues in a closed issue_**

**Comment by gfyre** [comment]
@smaharj1 Apologies for adding multiple issues into one close issue. I'll bear this in mind.

What I meant by "I keep on getting logged out of the dashboard. After some time, it just doesn't allow me to do anything and refreshing the page logs me out." is it logs me out when I am trying to do something. It all of a sudden shows me just "Catalogue" in the left-hand nav and then upon refreshing the page, I am logged out.
